apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorecalifornia
  name: explorecalifornia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorecalifornia
  strategy: {}
  template:
    metadata:
      labels:
        app: explorecalifornia
    spec:
      containers:
      - image: localhost:5000/explorecalifornia
        name: explorecalifornia
        resources: {}
status: {}
